spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.24.176.228:3306/test?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 120.24.176.228
    password: 123456


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
